/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PetitionImport } from './routes/petition'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const PetitionRoute = PetitionImport.update({
  id: '/petition',
  path: '/petition',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/petition': {
      id: '/petition'
      path: '/petition'
      fullPath: '/petition'
      preLoaderRoute: typeof PetitionImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/petition': typeof PetitionRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/petition': typeof PetitionRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/petition': typeof PetitionRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/petition'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/petition'
  id: '__root__' | '/' | '/petition'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PetitionRoute: typeof PetitionRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PetitionRoute: PetitionRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/petition"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/petition": {
      "filePath": "petition.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
